name: music_play
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
